name: sms_plus
description: A Flutter plugin to Send SMS and MMS on iOS and Android. If iMessage is enabled it will send as iMessage on iOS. This plugin must be tested on a real device on iOS.
version: 3.0.0
homepage: https://github.com/chandrabezzo
repository: https://github.com/chandrabezzo/sms_plus
maintainer: Chandra Abdul Fattah

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  url_launcher: ^6.0.3
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_sms
        pluginClass: FlutterSmsPlugin
      ios:
        pluginClass: FlutterSmsPlugin
      web:
        pluginClass: FlutterSmsPlugin
        fileName: flutter_sms_web.dart
